version: "3"

services:
  nodemailer:
    build: .
    image: node:12.16.3
    container_name: nodemailer
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    command: npm start